sudo: required
services:
  - docker
before_install:
  - docker build -t praveenkumarkilari83/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true praveenkumarkilari83/react-test npm run test
