sudo: required
services:
  - docker
before_install:
  - docker build -t sbaiskht/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sbaiskht/react-test npm run test
after_success:
  - docker build -t sbaiskht/multi-client ./client
  - docker build -t sbaiskht/multi-server ./server
  - docker build -t sbaiskht/multi-nginx ./nginx
  - docker build -t sbaiskht/multi-worker ./worker
  # Docker Login with credential
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to dockerhub
  - docker push sbaiskht/multi-client
  - docker push sbaiskht/multi-server
  - docker push sbaiskht/multi-nginx
  - docker push sbaiskht/multi-worker
