sudo: required
services:
  - docker
before_install:
  - docker build -t praveenkumarkilari83/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true praveenkumarkilari83/react-test npm run test
after_success:
  - docker build -t praveenkumarkilari83/multi-client ./client
  - docker build -t praveenkumarkilari83/multi-server ./server
  - docker build -t praveenkumarkilari83/multi-nginx ./nginx
  - docker build -t praveenkumarkilari83/multi-worker ./worker
# Docker Login with credential
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
# Take those images and push them to dockerhub
docker push praveenkumarkilari83/multi-client
docker push praveenkumarkilari83/multi-server
docker push praveenkumarkilari83/multi-nginx
docker push praveenkumarkilari83/multi-worker
